# Generated by Django 3.2 on 2021-06-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_alter_produit_emballag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Type',
            field=models.CharField(choices=[('em', 'emballé'), ('Ne', 'Nom emballé')], default='cs', max_length=2),
        ),
    ]
